ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Mailbox

Mailbox -- сервис обмена письмами

* Клиенты подключаются к серверу, отправляют или читают письма
* Сервер принимает, хранит и отправляет письма клиентам

== Примеры взаимодействия

=== Отправка письма

[source,text]
----
Введите IP-адрес и порт сервера:
> 1.1.1.1 8888

Подключение успешно, введите Ваше имя:
> anon

Привет, anon.

1. Просмотреть входящие письма
2. Отправить письмо
3. Выйти

> 2

Введите имя получателя:
> anon2
Введите текст письма:
> Привет!
Письмо отправлено

1. Просмотреть входящие письма
2. Отправить письмо
3. Выйти
----

=== Просмотр письма

[source,text]
----
Введите IP-адрес и порт сервера:
> 1.1.1.1 8888

Подключение успешно, введите Ваше имя:
> anon2

Привет, anon2.

1. Просмотреть входящие письма
2. Отправить письмо
3. Выйти

> 1

Письмо от anon:

> Привет!

1. Просмотреть входящие письма
2. Отправить письмо
3. Выйти
> 3
До свидания
----

== Клиент и сервер

Mailbox -- клиент-серверное приложение

=== Сервер

. Принимает письма пользователей
.. Хранит принятые письма в памяти -- Java-коллекции
. Обслуживает одновременно несколько клиентов -- по одному потоку на клиент
. Выдаёт письма клиентам:
.. Клиент вводит своё имя при подключении к серверу
.. Сервер определяет клиента по имени
. Удаляет письма, если клиент их получил.
Пример:
.. anon отправляет письмо anon2
.. anon2 подключается к серверу
.. anon2 выбирает пункт «Просмотреть входящие письма»
.. anon2 читает письмо от anon
.. anon2 выбирает пункт «Просмотреть входящие письма»
.. anon2 видит пустой список

=== Клиент

. Подключается к серверу по IP-адресу и TCP-порту
. Взаимодействует с человеком:
.. Читает ввод: письма, выбор элементов меню
.. Выводит входящие письма

== О безопасности

Безопасности в «Mailbox» никакой нет 🤭.
Любой клиент может ввести имя другого пользователя и прочитать письма другого человека

== В результате

Две программы:

. Клиент
. Сервер

в каждой из программ -- свой метод `main`.

== Что вспомнить

. Потоки -- https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Thread.html[`java.lang.Thread`]
. https://habr.com/ru/company/luxoft/blog/157273/[`java.util.concurrent`]
. https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/Closeable.html[`Closeable`], например, https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/Socket.html[`Socket`], https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/InputStream.html[`InputStream`] надо https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/Closeable.html#close()[закрывать]
. Метод https://stackoverflow.com/q/2340106/6486622[`flush`]

== Что использовать

. https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/ServerSocket.html[`ServerSocket`]
. https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/Socket.html[`Socket`]

== Тесты

Покройте тестами просто всё, что считаете нужным.
Тесты -- это серьёзно, правда.

== Как сдавать

В двух частях:

* По полторы недели на каждую часть
* Одна часть -- одно мини-ДЗ
* Части -- без чётких границ:
** Делаем сколько получится в первой части, задаем вопросы, получаем ответы, получаем отметку
** Доводим до конца во второй, получаем вторую отметку

== Чек-лист проверки

Здесь я перечислю то, на что обязательно обращу внимание при проверке 🕵️, остальное -- по ходу дела

=== Проект

. Не пакет по умолчанию
. Форматирование кода

=== maven

. Запускает тесты.
Справка -- в https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven[JUnit5 User Guide]
. Не ругается на кодировку.
Посмотрите вопрос https://stackoverflow.com/q/24144073/6486622[«Why does Maven warn me about encoding?»]

=== Исключения

Никаких игнорирований!

Вот так нельзя:

[source,java]
----
try {
    // замечательный код <(￣︶￣)>
} catch (Exception e) {
    // (￢_￢;),
}
----

Так тоже:

[source,java]
----
try {
    // Чудо-код ヽ(・∀・)ﾉ
} catch (Exception e) {
    e.printStackTrace(); // 👿
}
----

=== Обработка ошибок

* На пользователя приложений не вываливаются stacktrace'ы без описания проблемы
* Пользователь по описанию проблемы может понять, что ему делать

==== Не ок

[source,text]
----
Введите имя хоста:

> asfasdfasdf

Exception in thread "main" java.net.UnknownHostException: asfasdfasdf
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
    at java.base/java.net.Socket.connect(Socket.java:633)
    at java.base/java.net.Socket.connect(Socket.java:583)
    at java.base/java.net.Socket.<init>(Socket.java:507)
    at java.base/java.net.Socket.<init>(Socket.java:287)
    at Main.main(Main.java:8)

Process finished with exit code 1
----

Почему не ок?::
Потому что программа завершила свою работу, а могла бы:
. Попросить пользователя повторно ввести имя хоста
. Объяснить, что нужно делать, чтобы программа заработала

==== Так ок

[source,text]
----
Введите имя хоста:

> asfasdfasdf

Не удалось подключиться к «asfasdfasdf»: неизвестное доменное имя.
Проверьте соединение и введите имя хоста ещё раз:

> mymailbox.com

(...)
----

==== Так тоже ок

[source,text]
----
Введите имя хоста:

> asfasdfasdf

Не удалось подключиться к «asfasdfasdf»: неизвестное доменное имя.
Exception in thread "main" java.net.UnknownHostException: asfasdfasdf
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
    at java.base/java.net.Socket.connect(Socket.java:633)
    at java.base/java.net.Socket.connect(Socket.java:583)
    at java.base/java.net.Socket.<init>(Socket.java:507)
    at java.base/java.net.Socket.<init>(Socket.java:287)
    at Main.main(Main.java:8)

Проверьте соединение и введите имя хоста ещё раз:

> mymailbox.com

(...)
----

=== IO

. Ресурсы: потоки и сокеты закрываются в случае исключений
. `flush` вызывается там, где нужно.

== Если хочется большего

. Разобраться с https://maven.apache.org/guides/mini/guide-multiple-modules.html[многомодульными проектами maven]
.. Настроить `pom.xml` так, чтобы `mvn package` собирал 2 исполняемых ``jar``'а: один -- для сервера, второй -- для клиента
. Написать `README.md` с:
.. Описанием, как работать с программой
.. Автором
. Добавить логирование серверу.
.. Посмотреть доклад https://www.youtube.com/watch?v=j-i3NQiKbcc[«Владимир Красильщик — Что надо знать о логировании прагматичному Java-программисту»]
.. Выбрать один из вариантов:
.. `java.util.logging` -- встроенный.
Ссылки:
... https://docs.oracle.com/javase/10/core/java-logging-overview.htm#JSCOR-GUID-B83B652C-17EA-48D9-93D2-563AE1FF8EDA[Java Logging Overview]
... https://stackoverflow.com/questions/11359187/why-not-use-java-util-logging[Why not use java.util.logging?]
.. https://logback.qos.ch/[Logback] -- сторонний

[NOTE]
====
Ссылки о `README.md` -- https://github.com/diligent-snail/javafx-time-homework/blob/main/TASK.md#readme[здесь]
====

[NOTE]
====
Само задание я оформил в другом формате -- https://asciidoctor.org/[asciidoctor]
====