= Отменяемые Числа Фибоначчи

== Задание

Добавить в программу класс с методом `main`, который:

. Спрашивает у пользователя число -- `n`
. Вычисляет и выводит `n`-е число Фибоначчи
. Отменяет вычисление и запускает новое, если пользователь не дождался, когда программа посчитает результат.
.. Поменяйте обработку флага прерывания в методе link:src/main/java/edu/cancellablefibonacci/Fibonacci.java[`Fibonacci#fibonacciOf`], чтобы вычисление прерывалось, если задачу отменили.
Иначе -- https://stackoverflow.com/q/28043225/6486622[future.cancel does not work]

=== Пример взаимодействия

[source,text]
----
Введите n или «exit»:
> 1
fibonacciOf(1) = 1
Введите n или «exit»:
> 100
Введите n или «exit»:
> 3 <1>
Вычисление отменено для n = 100
fibonacciOf(3) = 2
Введите n или «exit»:
> -3
n должно быть больше 0, а было равно '-3'
Введите n или «exit»:
> exit
Введите n или «exit»:
> Не строка
Введите число
Введите n или «exit»:
exit
До свидания
----

<1> Пользователь не дождался и ввёл `3`

== Что использовать

. https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ExecutorService.html[`ExecutorService`] -- для вычисления числа Фибоначчи, а именно -- https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Executors.html#newCachedThreadPool()[`Executors#newCachedThreadPool()`]
. link:src/main/java/edu/cancellablefibonacci/Fibonacci.java[`Fibonacci#fibonacciOf`] вычислит `n`-е число Фибоначчи
. https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Future.html#cancel(boolean)[`Future#cancel`] для отмены вычисления.
Вызываем с флагом `true`.
Если передать `false`, то вычисление прервано не будет.
См. также: https://stackoverflow.com/a/21445268/6486622[What does Future.cancel() do if not interrupting?]

== Возможные вопросы

[quanda]
Можно ли поменять метод `Fibonacci#fibonacciOf` так, чтобы он работал быстро?::
Нет 😄.
Метод специально работает медленно, чтобы был смысл отменять задачу
Можно ли поменять метод `Fibonacci#fibonacciOf` как-нибудь по-другому?::
Да
Можно ли поменять сообщения вывода? Например, вместо «До свидания» выводить «Пока»?::
Да, можно сделать так, как Вам нравится
Можно ли использовать ключевое слово `volatile`, `java.util.concurrent.locks.Lock`?::
Да, можно использовать всё что душе угодно, кроме сторонних библиотек.
В тестах можно и сторонние библиотеки
Тесты обязательно писать?::
Нет
Что делать, если ничего не понятно?::
Сделать задание так, как Вы поняли.
Если сделаете что-то неправильно, разберёмся вместе, как правильно

== Срок

До 26 января.
Это -- среда
